ALTER TABLE `tickets` ADD COLUMN trang_thai INT NOT NULL DEFAULT 0;
ALTER TABLE `coupons` ADD COLUMN trang_thai INT NOT NULL DEFAULT 0;
ALTER TABLE `events` ADD COLUMN trang_thai INT NOT NULL DEFAULT 0;