# Sử dụng một base image với Java và Maven
FROM maven:3.8.1-openjdk-11 AS build

# Copy mã nguồn vào container
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app

# Biên dịch ứng dụng
RUN mvn -f /usr/src/app/pom.xml clean package

# Sử dụng một image nhẹ hơn để chạy ứng dụng
FROM openjdk:11-jre-slim

# Copy file jar từ bước biên dịch trước
COPY --from=build /usr/src/app/target/your-application.jar /usr/app/your-application.jar

# Chạy ứng dụng khi container khởi động
ENTRYPOINT ["java","-jar","/usr/app/your-application.jar"]
