server:
  port: 8080
spring:
  flyway:
    check-location: true
    enabled: true
    locations: classpath:/db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: sa
    password: 123456
  jpa:
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
