server:
  port: 8080
spring:
  flyway:
    check-location: true
    enabled: true
    locations: classpath:/db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/ticket?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: sa
    password: 123456

payment:
  stripe:
    apiKey: sk_test_51JMTRuCTcmTzqVmXhn6vIOBg3WJ18ijGnLkQslPri9OolIFNw3ODBuWN89Bx9y8NGq2Ll1DWfHuxgILCl6pfGhpv00yZpbSQoF

